/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package crimemanagement;

import java.awt.HeadlessException;
import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Bhardwaj
 */
public class Citizensignup extends javax.swing.JFrame {

    /**
     * Creates new form Citizensignup
     */
    
    public Citizensignup() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        fn = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        ln = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        un = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        dobm = new javax.swing.JComboBox<>();
        doby = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        rm = new javax.swing.JRadioButton();
        rf = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        dobd = new javax.swing.JTextField();
        pass1 = new javax.swing.JPasswordField();
        pass2 = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(640, 480));
        setPreferredSize(new java.awt.Dimension(640, 480));
        setSize(new java.awt.Dimension(640, 480));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 0, 0));
        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 204));
        jLabel2.setText("SIGN UP");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(255, 11, 132, 43);

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel1.setText("First Name");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(32, 72, 99, 30);

        fn.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jPanel1.add(fn);
        fn.setBounds(135, 68, 140, 30);

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel3.setText("Last Name");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(313, 72, 99, 30);

        ln.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        ln.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lnActionPerformed(evt);
            }
        });
        jPanel1.add(ln);
        ln.setBounds(430, 70, 140, 30);

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel4.setText("Create a Username");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(32, 132, 156, 30);

        un.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jPanel1.add(un);
        un.setBounds(229, 128, 199, 30);

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel5.setText("Enter Password");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(32, 180, 156, 30);

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel6.setText("Confirm Password");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(32, 228, 156, 30);

        jLabel7.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel7.setText("Date Of Birth");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(32, 288, 85, 18);

        dobm.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        dobm.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Month", "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));
        dobm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dobmActionPerformed(evt);
            }
        });
        jPanel1.add(dobm);
        dobm.setBounds(220, 290, 120, 24);

        doby.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        doby.setText("Year");
        doby.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dobyActionPerformed(evt);
            }
        });
        jPanel1.add(doby);
        doby.setBounds(440, 290, 75, 24);

        jLabel8.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel8.setText("Gender");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(32, 341, 76, 18);

        rm.setBackground(new java.awt.Color(255, 0, 0));
        buttonGroup1.add(rm);
        rm.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        rm.setText("Male");
        jPanel1.add(rm);
        rm.setBounds(209, 337, 69, 27);

        rf.setBackground(new java.awt.Color(255, 0, 0));
        buttonGroup1.add(rf);
        rf.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        rf.setText("Female");
        jPanel1.add(rf);
        rf.setBounds(306, 337, 69, 27);

        jButton1.setBackground(new java.awt.Color(255, 0, 0));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Signup-Red-Button_small_png.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(193, 384, 122, 39);

        jButton3.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jButton3.setText("Cancel");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(365, 384, 95, 31);

        dobd.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        dobd.setText("Date");
        dobd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dobdActionPerformed(evt);
            }
        });
        jPanel1.add(dobd);
        dobd.setBounds(350, 290, 75, 24);

        pass1.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jPanel1.add(pass1);
        pass1.setBounds(230, 180, 200, 30);

        pass2.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jPanel1.add(pass2);
        pass2.setBounds(230, 230, 200, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 660, 480);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String fname=fn.getText();
        String lname=ln.getText();
        String pass=pass1.getText();
        String cpass=pass2.getText();
        String uname=un.getText();
        String gender="m";
        String User = null;
        if(rm.isSelected()){
            gender="Male";
        }
        else if(rf.isSelected()){
            gender="female";
        }
        try {
            Connection con=null;
            Class.forName("oracle.jdbc.driver.OracleDriver");
            con=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe", authorization.username,authorization.password);
            PreparedStatement pst=con.prepareStatement("Select *from userdetails where username=?");
            pst.setString(1, uname);
            ResultSet x=pst.executeQuery();
            while(x.next()){
                User=x.getString(1);
            }
            int maxdays[] = {0, 31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31};
            int mon = dobm.getSelectedIndex();
            int date = Integer.parseInt(dobd.getText());
            int year = Integer.parseInt(doby.getText());
            if ((year % 4) == 0) {
                maxdays[2] = 29;
            }
            if ((mon < 1) || (mon > 12) || (date < 1) || (date > maxdays[mon]) || year < 1900 || (year > 9999)) {
                JOptionPane.showMessageDialog(this, "Invalid Date of Birth");
            } else if (fname.length() < 3) {
                JOptionPane.showMessageDialog(this, "Invalid Name");
            } else if (uname.length() < 1) {
                JOptionPane.showMessageDialog(this, "Username Can not be Empty");
            } else if (uname.equals(User)){
                JOptionPane.showMessageDialog(this, "Username already Taken!");
            } else if (pass.length() < 1) {
                JOptionPane.showMessageDialog(this, "Password Can not be Empty");
            } else if (!(pass.equals(cpass))) {
                JOptionPane.showMessageDialog(this, "Password do not Match");
            } else if (gender.length() < 2) {
                JOptionPane.showMessageDialog(this, "Select Your Gender");
            } else {
                String dob=Integer.toString(date)+"/"+Integer.toString(mon)+"/"+Integer.toString(year);
                PreparedStatement ps=con.prepareStatement("Insert into userdetails values(?,?,?,?,?,?)");
                ps.setString(1, fname);
                ps.setString(2, lname);
                ps.setString(3, uname);
                ps.setString(4, pass);
                ps.setString(5, dob);
                ps.setString(6, gender);
                int y= ps.executeUpdate();
                if(y>0){
                    JOptionPane.showMessageDialog(this, "Sign Up Successful! Login Now");
                }
                con.close();
                this.dispose();
                new Citizenlogin().setVisible(true);
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this,"Invalid Date Format");
        } catch(ClassNotFoundException | SQLException | HeadlessException ex){
            JOptionPane.showMessageDialog(this,ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new Citizenlogin().setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void dobmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dobmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dobmActionPerformed

    private void dobyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dobyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dobyActionPerformed

    private void dobdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dobdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dobdActionPerformed

    private void lnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Citizensignup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Citizensignup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Citizensignup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Citizensignup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Citizensignup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField dobd;
    private javax.swing.JComboBox<String> dobm;
    private javax.swing.JTextField doby;
    private javax.swing.JTextField fn;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField ln;
    private javax.swing.JPasswordField pass1;
    private javax.swing.JPasswordField pass2;
    private javax.swing.JRadioButton rf;
    private javax.swing.JRadioButton rm;
    private javax.swing.JTextField un;
    // End of variables declaration//GEN-END:variables
}
