/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package crimemanagement;
import java.sql.*;
import javax.swing.JOptionPane;
/**
 *
 * @author Bhardwaj
 */
public class criminals extends javax.swing.JFrame {

    /**
     * Creates new form criminals
     */
    public criminals() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        firid = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        cr = new javax.swing.JLabel();
        ph = new javax.swing.JLabel();
        add = new javax.swing.JLabel();
        evd = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        na = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        arr = new javax.swing.JLabel();
        doc = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        cs = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        doarr = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(700, 600));
        setPreferredSize(new java.awt.Dimension(700, 600));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setText("CRIMINALS RECORDS");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(188, 11, 339, 42);

        jButton1.setForeground(new java.awt.Color(0, 0, 255));
        jButton1.setText("BACK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(0, 0, 70, 23);

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 255));
        jLabel2.setText("Enter FIR Code");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(130, 60, 119, 21);

        firid.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        firid.setForeground(new java.awt.Color(153, 0, 255));
        getContentPane().add(firid);
        firid.setBounds(310, 60, 229, 27);

        jButton2.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(51, 51, 255));
        jButton2.setText("SUBMIT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(310, 110, 79, 27);

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 255));
        jLabel5.setText("Phone No.");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(130, 270, 87, 21);

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 255));
        jLabel6.setText("Crime");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(130, 310, 49, 21);

        jLabel7.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 255));
        jLabel7.setText("Evidence");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(130, 350, 75, 21);

        jPanel1.setBackground(new java.awt.Color(204, 102, 255));
        jPanel1.setLayout(null);

        cr.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        cr.setForeground(new java.awt.Color(0, 0, 255));
        jPanel1.add(cr);
        cr.setBounds(310, 340, 221, 20);

        ph.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        ph.setForeground(new java.awt.Color(0, 0, 255));
        jPanel1.add(ph);
        ph.setBounds(310, 300, 221, 20);

        add.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        add.setForeground(new java.awt.Color(0, 0, 255));
        jPanel1.add(add);
        add.setBounds(310, 250, 221, 20);

        evd.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        evd.setForeground(new java.awt.Color(0, 0, 255));
        jPanel1.add(evd);
        evd.setBounds(310, 380, 221, 20);

        jLabel8.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 255));
        jLabel8.setText("Date Of Complaint");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(130, 500, 153, 21);

        jLabel9.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 255));
        jLabel9.setText("Date Of Arresting");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(130, 540, 146, 21);

        na.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        na.setForeground(new java.awt.Color(0, 0, 255));
        jPanel1.add(na);
        na.setBounds(310, 200, 205, 20);

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 255));
        jLabel3.setText("Name");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(130, 200, 47, 21);

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 255));
        jLabel4.setText("Address");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(130, 250, 65, 21);

        arr.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        arr.setForeground(new java.awt.Color(0, 0, 255));
        jPanel1.add(arr);
        arr.setBounds(311, 420, 220, 20);

        doc.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        doc.setForeground(new java.awt.Color(0, 0, 255));
        jPanel1.add(doc);
        doc.setBounds(310, 500, 221, 20);

        jLabel10.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 255));
        jLabel10.setText("Case Solved");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(130, 460, 110, 21);

        cs.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        cs.setForeground(new java.awt.Color(0, 0, 255));
        jPanel1.add(cs);
        cs.setBounds(310, 460, 221, 20);

        jLabel11.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 255));
        jLabel11.setText("Arrested");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(130, 420, 72, 21);

        doarr.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        doarr.setForeground(new java.awt.Color(0, 0, 255));
        jPanel1.add(doarr);
        doarr.setBounds(310, 540, 221, 20);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, -30, 700, 690);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String fname="a";
        String name=null,address=null,phone=null,crime=null,evidence=null,arrested=null,casesol=null,dateofcomp=null,dateofarrest=null;
           try{
               Connection con=null;
            Class.forName("oracle.jdbc.driver.OracleDriver");
            con=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe",authorization.username,authorization.password);
            PreparedStatement pst=con.prepareStatement("select *from firdetails where firid=?");
            pst.setString(1, firid.getText());
            ResultSet x= pst.executeQuery();
            while(x.next()){
                fname=x.getString(1);
                name=(fname+" "+ x.getString(2));
                address=(x.getString(3));
                phone=(x.getString(4));
                crime=(x.getString(5));
                evidence=(x.getString(7));
                arrested=(x.getString(9));
                casesol=(x.getString(10));
                dateofcomp=(x.getString(12));
                dateofarrest=(x.getString(11));
            }
            if(fname.equals("a")){
                JOptionPane.showMessageDialog(this, "FIR Code Not Found!");
            }
            else{
                na.setText(name);
                add.setText(address);
                ph.setText(phone);
                cr.setText(crime);
                evd.setText(evidence);
                arr.setText(arrested);
                cs.setText(casesol);
                doc.setText(dateofcomp);
                doarr.setText(dateofarrest);
            }
           }catch(Exception e){
               JOptionPane.showMessageDialog(this, e );
           }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new policepage().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(criminals.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(criminals.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(criminals.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(criminals.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new criminals().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel add;
    private javax.swing.JLabel arr;
    private javax.swing.JLabel cr;
    private javax.swing.JLabel cs;
    private javax.swing.JLabel doarr;
    private javax.swing.JLabel doc;
    private javax.swing.JLabel evd;
    private javax.swing.JTextField firid;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel na;
    private javax.swing.JLabel ph;
    // End of variables declaration//GEN-END:variables
}
