/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package crimemanagement;

import javax.swing.JOptionPane;
import java.sql.*;

/**
 *
 * @author Bhardwaj
 */
public class investigation extends javax.swing.JFrame {

    /**
     * Creates new form investigation
     */
    public investigation() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        fir = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        ps = new javax.swing.JLabel();
        evd = new javax.swing.JLabel();
        ph = new javax.swing.JLabel();
        cr = new javax.swing.JLabel();
        add = new javax.swing.JLabel();
        na = new javax.swing.JLabel();
        doc = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(640, 540));
        getContentPane().setLayout(null);

        jButton1.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(204, 0, 153));
        jButton1.setText("BACK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(0, 0, 65, 27);

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setText("CASES UNDER INVESTIGATION");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(99, 0, 490, 42);

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 255));
        jLabel2.setText("Enter FIR Code");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(99, 88, 124, 21);

        fir.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        fir.setForeground(new java.awt.Color(153, 51, 255));
        getContentPane().add(fir);
        fir.setBounds(252, 85, 158, 27);

        jButton2.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(204, 0, 0));
        jButton2.setText("SUBMIT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(209, 143, 93, 29);

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 255));
        jLabel3.setText("Name");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(144, 198, 47, 21);

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 255));
        jLabel4.setText("Address");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(144, 237, 65, 21);

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 255));
        jLabel5.setText("Phone No.");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(144, 276, 87, 21);

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 255));
        jLabel6.setText("Crime");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(144, 315, 49, 21);

        jLabel7.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 255));
        jLabel7.setText("Evidence");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(144, 354, 75, 21);

        jLabel8.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 255));
        jLabel8.setText("Police Station");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(144, 393, 114, 21);

        jLabel9.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 255));
        jLabel9.setText("Date of Complaint");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(144, 432, 150, 21);

        ps.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        ps.setForeground(new java.awt.Color(0, 0, 255));
        getContentPane().add(ps);
        ps.setBounds(363, 393, 150, 21);

        evd.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        evd.setForeground(new java.awt.Color(0, 0, 255));
        getContentPane().add(evd);
        evd.setBounds(363, 354, 150, 21);

        ph.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        ph.setForeground(new java.awt.Color(0, 0, 255));
        getContentPane().add(ph);
        ph.setBounds(363, 276, 150, 21);

        cr.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        cr.setForeground(new java.awt.Color(0, 0, 255));
        getContentPane().add(cr);
        cr.setBounds(363, 315, 150, 21);

        add.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        add.setForeground(new java.awt.Color(0, 0, 255));
        getContentPane().add(add);
        add.setBounds(363, 237, 150, 21);

        na.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        na.setForeground(new java.awt.Color(0, 0, 255));
        getContentPane().add(na);
        na.setBounds(363, 198, 150, 21);

        doc.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        doc.setForeground(new java.awt.Color(0, 0, 255));
        getContentPane().add(doc);
        doc.setBounds(363, 423, 270, 30);

        jPanel1.setBackground(new java.awt.Color(204, 255, 102));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 640, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 560, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 640, 560);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new policepage().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String firid=fir.getText();
        String casesol="a";
        String name=null,address=null,phone=null,crime=null,evidence=null,police=null,dateofcomp=null;
        try{
            Connection con=null;
            Class.forName("oracle.jdbc.driver.OracleDriver");
            con=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe",authorization.username,authorization.password);
            PreparedStatement pst=con.prepareStatement("select *from firdetails where firid=?");
            pst.setString(1, firid);
            ResultSet x=pst.executeQuery();
            while(x.next()){
                casesol=x.getString(10);
                name=(x.getString(1)+" "+ x.getString(2));
                address=(x.getString(3));
                phone=(x.getString(4));
                crime=(x.getString(5));
                evidence=(x.getString(7));
                police=(x.getString(8));
                dateofcomp=(x.getString(12));
                }
            if(casesol.equals("a")){
                JOptionPane.showMessageDialog(this, "FIR Code Not Found!");
            }
            else if(casesol.equals("YES")){
                JOptionPane.showMessageDialog(this, "This case Is Solved!");
            }
            else{
                na.setText(name);
                add.setText(address);
                ph.setText(phone);
                cr.setText(crime);
                evd.setText(evidence);
                ps.setText(police);
                doc.setText(dateofcomp);
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(this,e);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(investigation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(investigation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(investigation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(investigation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new investigation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel add;
    private javax.swing.JLabel cr;
    private javax.swing.JLabel doc;
    private javax.swing.JLabel evd;
    private javax.swing.JTextField fir;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel na;
    private javax.swing.JLabel ph;
    private javax.swing.JLabel ps;
    // End of variables declaration//GEN-END:variables
}
