/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package crimemanagement;

import javax.swing.JOptionPane;

/**
 *
 * @author Bhardwaj
 */
public class policepage extends javax.swing.JFrame {

    /**
     * Creates new form policepage
     */
    public policepage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        rb1 = new javax.swing.JRadioButton();
        rb3 = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        rb2 = new javax.swing.JRadioButton();
        jButton2 = new javax.swing.JButton();
        rb4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Crime Management System");
        setMinimumSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(null);

        jButton1.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jButton1.setText("LOG OUT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(10, 11, 83, 23);

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 255, 0));
        jLabel1.setText("HOME PAGE");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(289, 40, 261, 57);

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 0, 204));
        jLabel2.setText("Select an Option");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(100, 115, 186, 29);

        rb1.setBackground(new java.awt.Color(153, 153, 255));
        buttonGroup1.add(rb1);
        rb1.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        rb1.setForeground(new java.awt.Color(0, 0, 153));
        rb1.setText("Update Case Details");
        getContentPane().add(rb1);
        rb1.setBounds(122, 162, 191, 29);

        rb3.setBackground(new java.awt.Color(153, 153, 255));
        buttonGroup1.add(rb3);
        rb3.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        rb3.setForeground(new java.awt.Color(0, 0, 153));
        rb3.setText("Cases Solved");
        getContentPane().add(rb3);
        rb3.setBounds(122, 256, 131, 29);

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));
        jPanel1.setLayout(null);

        rb2.setBackground(new java.awt.Color(153, 153, 255));
        buttonGroup1.add(rb2);
        rb2.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        rb2.setForeground(new java.awt.Color(0, 0, 153));
        rb2.setText("View Criminal records");
        rb2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb2ActionPerformed(evt);
            }
        });
        jPanel1.add(rb2);
        rb2.setBounds(120, 210, 230, 29);

        jButton2.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 0, 0));
        jButton2.setText("SUBMIT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(400, 410, 93, 29);

        rb4.setBackground(new java.awt.Color(153, 153, 255));
        buttonGroup1.add(rb4);
        rb4.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        rb4.setForeground(new java.awt.Color(0, 0, 153));
        rb4.setText("Cases Under Investigation");
        rb4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb4ActionPerformed(evt);
            }
        });
        jPanel1.add(rb4);
        rb4.setBounds(120, 300, 250, 29);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 800, 600);

        jRadioButton5.setBackground(new java.awt.Color(153, 153, 255));
        buttonGroup1.add(jRadioButton5);
        jRadioButton5.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jRadioButton5.setForeground(new java.awt.Color(0, 0, 153));
        jRadioButton5.setText("Criminal Records");
        getContentPane().add(jRadioButton5);
        jRadioButton5.setBounds(122, 303, 167, 29);

        jRadioButton6.setBackground(new java.awt.Color(153, 153, 255));
        buttonGroup1.add(jRadioButton6);
        jRadioButton6.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jRadioButton6.setForeground(new java.awt.Color(0, 0, 153));
        jRadioButton6.setText("Criminal Records");
        getContentPane().add(jRadioButton6);
        jRadioButton6.setBounds(122, 303, 167, 29);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rb4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if(rb1.isSelected()){
            this.dispose();
            new updatecase().setVisible(true);
        }
        else if(rb2.isSelected()){
            this.dispose();
            new criminals().setVisible(true);
        }
        else if(rb3.isSelected()){
             this.dispose();
             new case_solved().setVisible(true);
        }
        else if(rb4.isSelected()){
            this.dispose();
            new investigation().setVisible(true);
        }
        else{
            JOptionPane.showMessageDialog(this,"Select any Option");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void rb2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
       this.dispose();
       new home().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(policepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(policepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(policepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(policepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new policepage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton rb1;
    private javax.swing.JRadioButton rb2;
    private javax.swing.JRadioButton rb3;
    private javax.swing.JRadioButton rb4;
    // End of variables declaration//GEN-END:variables
}
